# SELECT *
# FROM ECOLI_DATA A
#     LEFT JOIN ECOLI_DATA B ON A.ID = B.PARENT_ID  # 자기 자신과 LEFT JOIN 하는 게 핵심
# ;

SELECT A.ID, COUNT(B.PARENT_ID) AS CHILD_COUNT
FROM ECOLI_DATA A
    LEFT JOIN ECOLI_DATA B ON A.ID = B.PARENT_ID
# WHERE COALESCE (B.PARENT_ID, "0") -- WHERE절 실행 시, 자식이 없는 ID 3의 경우는 아예 선택되지 않기 때문에 결과에서 빠지게 되므로 사용하면 안됨.
GROUP BY A.ID, B.PARENT_ID
ORDER BY A.ID ASC
;


