SELECT F.FLAVOR 
FROM FIRST_HALF F
    JOIN ICECREAM_INFO I ON F.FLAVOR = I.FLAVOR
WHERE F.TOTAL_ORDER > 3000 AND I.INGREDIENT_TYPE = 'fruit_based'  
    -- 문자열은 ' '를 사용
    -- 컬럼, 테이블 명 에 공백이 있을 경우 " " 를 사용
ORDER BY F.TOTAL_ORDER DESC
;