SELECT 
    P.PRODUCT_CODE AS PRODUCT_CODE, 
    SUM(P.PRICE * OS.SALES_AMOUNT) AS SALES
FROM PRODUCT AS P
    JOIN OFFLINE_SALE AS OS ON P.PRODUCT_ID = OS.PRODUCT_ID
GROUP BY P.PRODUCT_CODE
ORDER BY SALES DESC, PRODUCT_CODE ASC
;