SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES 
FROM 
    BOOK AS B
    JOIN BOOK_SALES AS BS ON B.BOOK_ID = BS.BOOK_ID
WHERE 
    # BS.SALES_DATE >= '2022-01-01' AND BS.SALES_DATE < '2022-02-01'
    BS.SALES_DATE LIKE '2022-01-%'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY ASC;