SELECT FIRST_HALF.FLAVOR 
FROM FIRST_HALF LEFT JOIN ICECREAM_INFO ON FIRST_HALF.FLAVOR = ICECREAM_INFO.FLAVOR
WHERE FIRST_HALF.TOTAL_ORDER > 3000
AND ICECREAM_INFO.INGREDIENT_TYPE = 'fruit_based'  
    -- 문자열은 ' '를 사용
    -- 컬럼, 테이블 명 에 공백이 있을 경우 " " 를 사용
ORDER BY FIRST_HALF.TOTAL_ORDER DESC
;